import type { NotificationPayloadDto, PostContentDto } from '@repo/shared-dto';
import { sql } from 'drizzle-orm';
import {
  boolean,
  foreignKey,
  jsonb,
  pgEnum,
  pgTable,
  pgView,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
  vector,
} from 'drizzle-orm/pg-core';

/** Dimensionality of the OpenAI text-embedding-3-small model. */
export const EMBEDDING_DIMENSIONS = 1536;

export const posts = pgTable('posts', {
  id: uuid('id').defaultRandom().primaryKey(),
  authorId: text('author_id').notNull(),
  content: jsonb('content').$type<PostContentDto>().notNull(),
  /** 1536-dimension vector embedding generated by OpenAI text-embedding-3-small. */
  embedding: vector('embedding', { dimensions: EMBEDDING_DIMENSIONS }),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

/**
 * Stores user avatar URLs separately from Better Auth's `user` table.
 * Better Auth does not persist the `image` field to the DB in this project,
 * so we own avatar storage ourselves.
 */
export const userProfiles = pgTable('user_profiles', {
  userId: text('user_id').primaryKey(),
  avatarUrl: text('avatar_url'),
});

export type UserProfile = typeof userProfiles.$inferSelect;
export type NewUserProfile = typeof userProfiles.$inferInsert;

/**
 * A read-only view over the better-auth `user` table joined with `user_profiles`.
 * Exposes only the fields needed by the application features.
 * The underlying `user` table is managed by better-auth migrations.
 */
export const usersView = pgView('users_view', {
  id: text('id').notNull(),
  username: text('username'),
  email: text('email').notNull(),
  name: text('name'),
  image: text('image'),
}).as(
  sql`SELECT u.id, u.username, u.email, u.name, up.avatar_url AS image FROM "user" u LEFT JOIN user_profiles up ON up.user_id = u.id`,
);

export type UserView = typeof usersView.$inferSelect;

export const reactionTypeEnum = pgEnum('reaction_type', ['upvote', 'downvote']);

export const postReactions = pgTable(
  'post_reactions',
  {
    postId: uuid('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    type: reactionTypeEnum('type').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.postId, table.userId] })],
);

export type PostReaction = typeof postReactions.$inferSelect;
export type NewPostReaction = typeof postReactions.$inferInsert;

export const comments = pgTable(
  'comments',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    postId: uuid('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    parentId: uuid('parent_id'),
    authorId: text('author_id').notNull(),
    content: text('content').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.parentId],
      foreignColumns: [table.id],
      name: 'comments_parent_id_fkey',
    }).onDelete('cascade'),
  ],
);

export type Comment = typeof comments.$inferSelect;
export type NewComment = typeof comments.$inferInsert;

export const commentReactions = pgTable(
  'comment_reactions',
  {
    commentId: uuid('comment_id')
      .notNull()
      .references(() => comments.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    type: reactionTypeEnum('type').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.commentId, table.userId] })],
);

export type CommentReaction = typeof commentReactions.$inferSelect;
export type NewCommentReaction = typeof commentReactions.$inferInsert;

export const userFollows = pgTable(
  'user_follows',
  {
    followerId: text('follower_id').notNull(),
    followeeId: text('followee_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.followerId, table.followeeId] })],
);

export type UserFollow = typeof userFollows.$inferSelect;
export type NewUserFollow = typeof userFollows.$inferInsert;

export const pollVotes = pgTable(
  'poll_votes',
  {
    postId: uuid('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    optionId: text('option_id').notNull(),
    userId: text('user_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.postId, table.optionId, table.userId] }),
  ],
);

export type PollVote = typeof pollVotes.$inferSelect;
export type NewPollVote = typeof pollVotes.$inferInsert;

export const threads = pgTable('threads', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: text('user_id').notNull(),
  title: text('title'),
  isArchived: boolean('is_archived').default(false).notNull(),
  externalId: text('external_id'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Thread = typeof threads.$inferSelect;
export type NewThread = typeof threads.$inferInsert;

/**
 * Direct message type enum — extensible for future types (image, file, etc.)
 */
export const directMessageTypeEnum = pgEnum('direct_message_type', ['text']);

/**
 * Represents a 1-on-1 conversation between two users.
 * user_a_id is always the lexicographically smaller user ID to ensure uniqueness.
 */
export const conversations = pgTable(
  'conversations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    userAId: text('user_a_id').notNull(),
    userBId: text('user_b_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique('conversations_user_pair_unique').on(table.userAId, table.userBId),
  ],
);

export type Conversation = typeof conversations.$inferSelect;
export type NewConversation = typeof conversations.$inferInsert;

/**
 * Individual direct messages within a conversation.
 * Includes nullable columns for future features (read receipts, soft delete, attachments).
 */
export const directMessages = pgTable('direct_messages', {
  id: uuid('id').defaultRandom().primaryKey(),
  conversationId: uuid('conversation_id')
    .notNull()
    .references(() => conversations.id, { onDelete: 'cascade' }),
  senderId: text('sender_id').notNull(),
  content: text('content').notNull(),
  type: directMessageTypeEnum('type').default('text').notNull(),
  /** Reserved for future read receipt support — null means unread */
  readAt: timestamp('read_at', { withTimezone: true }),
  /** Reserved for future soft-delete / message editing support */
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type DirectMessage = typeof directMessages.$inferSelect;
export type NewDirectMessage = typeof directMessages.$inferInsert;

// ─── Notifications ────────────────────────────────────────────────────────────

/**
 * Notification type enum — covers all social interaction events.
 */
export const notificationTypeEnum = pgEnum('notification_type', [
  'follow',
  'comment',
  'reply',
  'post_reaction',
  'comment_reaction',
  'direct_message',
]);

/**
 * Persisted notifications for each recipient user.
 * actorId is the user who triggered the event (null for system notifications).
 * payload is a JSONB blob whose shape is determined by `type`.
 */
export const notifications = pgTable('notifications', {
  id: uuid('id').defaultRandom().primaryKey(),
  /** The user who should receive this notification. */
  userId: text('user_id').notNull(),
  /** The user who triggered the event (follower, commenter, reactor, sender). */
  actorId: text('actor_id'),
  type: notificationTypeEnum('type').notNull(),
  /** Type-specific context data — see NotificationPayloadDto in shared-dto. */
  payload: jsonb('payload').$type<NotificationPayloadDto>().notNull(),
  /** null = unread */
  readAt: timestamp('read_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;

// ─── App Config ───────────────────────────────────────────────────────────────

/**
 * Persisted application configuration, stored per namespace.
 * Each row holds a JSONB blob for one top-level config namespace
 * (e.g. 'feed', 'ai', 'uploads'). Missing namespaces fall back to
 * schema defaults defined in AppConfigSchema.
 */
export const appConfig = pgTable('app_config', {
  namespace: text('namespace').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type AppConfigRow = typeof appConfig.$inferSelect;
export type NewAppConfigRow = typeof appConfig.$inferInsert;
