import type { NotificationPayloadDto, PostContentDto } from "@repo/shared-dto";
import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  doublePrecision,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  pgView,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

/** Dimensionality of the OpenAI text-embedding-3-small model. */
export const EMBEDDING_DIMENSIONS = 1536;

/**
 * Q&A primitive: distinguishes a help-seeking "question" from a regular
 * "discussion" post. Only questions expose the solved/accepted-answer surface.
 */
export const postKindEnum = pgEnum("post_kind", ["discussion", "question"]);

export const posts = pgTable("posts", {
  id: uuid("id").defaultRandom().primaryKey(),
  authorId: text("author_id").notNull(),
  content: jsonb("content").$type<PostContentDto>().notNull(),
  kind: postKindEnum("kind").default("discussion").notNull(),
  /** 1536-dimension vector embedding generated by OpenAI text-embedding-3-small. */
  embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
  contentHash: text("content_hash"),
  hidden: boolean("hidden").default(false).notNull(),
  /**
   * Q&A primitive: the comment the asker accepted as the answer. Plain uuid
   * (no FK) to avoid a posts↔comments cycle; cleared by the comments service
   * when the accepted comment is deleted.
   */
  acceptedCommentId: uuid("accepted_comment_id"),
  /** Q&A primitive: set when a question is marked solved (an answer accepted). */
  solvedAt: timestamp("solved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

// ─── Tags ────────────────────────────────────────────────────────────────────

export const tags = pgTable("tags", {
  id: uuid("id").defaultRandom().primaryKey(),
  slug: text("slug").notNull().unique(),
  displayName: text("display_name").notNull(),
  postCount: integer("post_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Tag = typeof tags.$inferSelect;
export type NewTag = typeof tags.$inferInsert;

export const postTags = pgTable(
  "post_tags",
  {
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    authorId: text("author_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.postId, table.tagId] }),
    index("idx_post_tags_tag_timeline").on(
      table.tagId,
      table.createdAt,
      table.postId,
    ),
    index("idx_post_tags_post").on(table.postId),
  ],
);

export type PostTag = typeof postTags.$inferSelect;

export const tagDailyStats = pgTable(
  "tag_daily_stats",
  {
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    day: date("day").notNull(),
    postCount: integer("post_count").notNull().default(0),
  },
  (table) => [primaryKey({ columns: [table.tagId, table.day] })],
);

export const tagPreferenceKindEnum = pgEnum("tag_preference_kind", [
  "preferred",
  "blocked",
]);

export const userTagPreferences = pgTable(
  "user_tag_preferences",
  {
    userId: text("user_id").notNull(),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    preference: tagPreferenceKindEnum("preference").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.tagId] }),
    index("idx_user_tag_preferences_user_preference").on(
      table.userId,
      table.preference,
    ),
    index("idx_user_tag_preferences_tag").on(table.tagId),
  ],
);

export type UserTagPreference = typeof userTagPreferences.$inferSelect;
export type NewUserTagPreference = typeof userTagPreferences.$inferInsert;

/**
 * Stores user avatar URLs separately from Better Auth's `user` table.
 * Better Auth does not persist the `image` field to the DB in this project,
 * so we own avatar storage ourselves.
 */
export const userProfiles = pgTable("user_profiles", {
  userId: text("user_id").primaryKey(),
  avatarUrl: text("avatar_url"),
  coverPhotoUrl: text("cover_photo_url"),
  bio: text("bio"),
});

export type UserProfile = typeof userProfiles.$inferSelect;
export type NewUserProfile = typeof userProfiles.$inferInsert;

/**
 * A read-only view over the better-auth `user` table joined with `user_profiles`.
 * Exposes only the fields needed by the application features.
 * The underlying `user` table is managed by better-auth migrations.
 */
export const usersView = pgView("users_view", {
  id: text("id").notNull(),
  username: text("username"),
  email: text("email").notNull(),
  name: text("name"),
  image: text("image"),
}).as(
  sql`SELECT u.id, u.username, u.email, u.name, up.avatar_url AS image FROM "user" u LEFT JOIN user_profiles up ON up.user_id = u.id`,
);

export type UserView = typeof usersView.$inferSelect;

export const reactionTypeEnum = pgEnum("reaction_type", ["upvote", "downvote"]);

export const postReactions = pgTable(
  "post_reactions",
  {
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    type: reactionTypeEnum("type").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.postId, table.userId] })],
);

export type PostReaction = typeof postReactions.$inferSelect;
export type NewPostReaction = typeof postReactions.$inferInsert;

export const postSubscriptions = pgTable(
  "post_subscriptions",
  {
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.postId, table.userId] })],
);

export type PostSubscription = typeof postSubscriptions.$inferSelect;
export type NewPostSubscription = typeof postSubscriptions.$inferInsert;

export const postBookmarks = pgTable(
  "post_bookmarks",
  {
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.postId, table.userId] })],
);

export type PostBookmark = typeof postBookmarks.$inferSelect;
export type NewPostBookmark = typeof postBookmarks.$inferInsert;

export const comments = pgTable(
  "comments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    parentId: uuid("parent_id"),
    authorId: text("author_id").notNull(),
    content: text("content").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.parentId],
      foreignColumns: [table.id],
      name: "comments_parent_id_fkey",
    }).onDelete("cascade"),
  ],
);

export type Comment = typeof comments.$inferSelect;
export type NewComment = typeof comments.$inferInsert;

export const commentReactions = pgTable(
  "comment_reactions",
  {
    commentId: uuid("comment_id")
      .notNull()
      .references(() => comments.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    type: reactionTypeEnum("type").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.commentId, table.userId] })],
);

export type CommentReaction = typeof commentReactions.$inferSelect;
export type NewCommentReaction = typeof commentReactions.$inferInsert;

export const userFollows = pgTable(
  "user_follows",
  {
    followerId: text("follower_id").notNull(),
    followeeId: text("followee_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.followerId, table.followeeId] })],
);

export type UserFollow = typeof userFollows.$inferSelect;
export type NewUserFollow = typeof userFollows.$inferInsert;

export const pollVotes = pgTable(
  "poll_votes",
  {
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    optionId: text("option_id").notNull(),
    userId: text("user_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.postId, table.optionId, table.userId] }),
  ],
);

export type PollVote = typeof pollVotes.$inferSelect;
export type NewPollVote = typeof pollVotes.$inferInsert;

export const threads = pgTable("threads", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  title: text("title"),
  isArchived: boolean("is_archived").default(false).notNull(),
  externalId: text("external_id"),
  /** Persisted chat messages for this thread, stored as an ordered JSONB array. */
  messages: jsonb("messages").$type<unknown[]>().default([]).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Thread = typeof threads.$inferSelect;
export type NewThread = typeof threads.$inferInsert;

/**
 * Direct message type enum — extensible for future types (image, file, etc.)
 */
export const directMessageTypeEnum = pgEnum("direct_message_type", ["text"]);

/**
 * Represents a 1-on-1 conversation between two users.
 * user_a_id is always the lexicographically smaller user ID to ensure uniqueness.
 */
export const conversations = pgTable(
  "conversations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userAId: text("user_a_id").notNull(),
    userBId: text("user_b_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("conversations_user_pair_unique").on(table.userAId, table.userBId),
  ],
);

export type Conversation = typeof conversations.$inferSelect;
export type NewConversation = typeof conversations.$inferInsert;

/**
 * Individual direct messages within a conversation.
 * Includes nullable columns for future features (read receipts, soft delete, attachments).
 */
export const directMessages = pgTable("direct_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  conversationId: uuid("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  senderId: text("sender_id").notNull(),
  content: text("content").notNull(),
  type: directMessageTypeEnum("type").default("text").notNull(),
  /** Reserved for future read receipt support — null means unread */
  readAt: timestamp("read_at", { withTimezone: true }),
  /** Reserved for future soft-delete / message editing support */
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type DirectMessage = typeof directMessages.$inferSelect;
export type NewDirectMessage = typeof directMessages.$inferInsert;

// ─── Notifications ────────────────────────────────────────────────────────────

/**
 * Notification type enum — covers all social interaction events.
 */
export const notificationTypeEnum = pgEnum("notification_type", [
  "follow",
  "comment",
  "reply",
  "post_update",
  "post_reaction",
  "comment_reaction",
  "direct_message",
  "post_hidden",
  "answer_accepted",
]);

/**
 * Persisted notifications for each recipient user.
 * actorId is the user who triggered the event (null for system notifications).
 * payload is a JSONB blob whose shape is determined by `type`.
 */
export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  /** The user who should receive this notification. */
  userId: text("user_id").notNull(),
  /** The user who triggered the event (follower, commenter, reactor, sender). */
  actorId: text("actor_id"),
  type: notificationTypeEnum("type").notNull(),
  /** Type-specific context data — see NotificationPayloadDto in shared-dto. */
  payload: jsonb("payload").$type<NotificationPayloadDto>().notNull(),
  /** null = unread */
  readAt: timestamp("read_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;

// ─── App Config ───────────────────────────────────────────────────────────────

/**
 * Persisted application configuration, stored per namespace.
 * Each row holds a JSONB blob for one top-level config namespace
 * (e.g. 'feed', 'ai', 'uploads'). Missing namespaces fall back to
 * schema defaults defined in AppConfigSchema.
 */
export const appConfig = pgTable("app_config", {
  namespace: text("namespace").primaryKey(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type AppConfigRow = typeof appConfig.$inferSelect;
export type NewAppConfigRow = typeof appConfig.$inferInsert;

// ─── Content Moderation ──────────────────────────────────────────────────────

/**
 * Status of a moderation record.
 */
export const moderationStatusEnum = pgEnum("moderation_status", [
  "pending",
  "approved",
  "rejected",
  "needs_human_review",
]);

/**
 * Source that triggered the moderation record.
 */
export const moderationSourceEnum = pgEnum("moderation_source", [
  "auto_duplicate",
  "auto_harmful",
  "user_report",
  "admin_flag",
]);

/**
 * Priority level for flagged posts.
 */
export const flagPriorityEnum = pgEnum("flag_priority", [
  "low",
  "medium",
  "high",
  "critical",
]);

/**
 * Reasons a user can report a post.
 */
export const reportReasonEnum = pgEnum("report_reason", [
  "spam",
  "harassment",
  "misinformation",
  "hate_speech",
  "violence",
  "inappropriate",
  "copyright",
  "other",
]);

/**
 * Central moderation record for a post. Each moderation event
 * (duplicate detection, harmful content, user report, admin flag)
 * creates a separate row here.
 */
export const postModeration = pgTable("post_moderation", {
  id: uuid("id").defaultRandom().primaryKey(),
  postId: uuid("post_id")
    .notNull()
    .references(() => posts.id, { onDelete: "cascade" }),
  /** Which pipeline step or action created this record. */
  source: moderationSourceEnum("source").notNull(),
  /** Current status of this moderation record. */
  status: moderationStatusEnum("status").default("pending").notNull(),
  /** Priority level — 'critical' instantly hides the post. */
  priority: flagPriorityEnum("priority").default("medium").notNull(),
  /** LLM confidence score (1-100), null if no LLM step ran. */
  llmConfidence: text("llm_confidence"),
  /** LLM-generated summary of why the post was flagged. */
  llmSummary: text("llm_summary"),
  /** ID of the most similar post (for duplicate detection). */
  similarPostId: uuid("similar_post_id"),
  /** Cosine similarity score (for duplicate detection). */
  similarityScore: text("similarity_score"),
  /** Raw moderation result from OpenAI (for harmful content). */
  moderationResult: jsonb("moderation_result"),
  /** Admin who reviewed, or null if not yet reviewed. */
  reviewedBy: text("reviewed_by"),
  /** When the record was reviewed. */
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  /** Admin's review note. */
  reviewNote: text("review_note"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type PostModeration = typeof postModeration.$inferSelect;
export type NewPostModeration = typeof postModeration.$inferInsert;

/**
 * User-submitted reports for posts.
 */
export const postReports = pgTable("post_reports", {
  id: uuid("id").defaultRandom().primaryKey(),
  postId: uuid("post_id")
    .notNull()
    .references(() => posts.id, { onDelete: "cascade" }),
  /** The user who submitted the report. */
  reporterId: text("reporter_id").notNull(),
  /** Reason category. */
  reason: reportReasonEnum("reason").notNull(),
  /** Free-text description from the reporter. */
  description: text("description"),
  /** Whether this report passed the gibberish heuristic check. */
  passedHeuristic: boolean("passed_heuristic").default(true).notNull(),
  /** Link to the moderation record created from this report, if any. */
  moderationId: uuid("moderation_id").references(() => postModeration.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type PostReport = typeof postReports.$inferSelect;
export type NewPostReport = typeof postReports.$inferInsert;

/**
 * Admin flags on posts — allows admins to manually flag posts
 * with different priority levels.
 */
export const postFlags = pgTable("post_flags", {
  id: uuid("id").defaultRandom().primaryKey(),
  postId: uuid("post_id")
    .notNull()
    .references(() => posts.id, { onDelete: "cascade" }),
  /** The admin who flagged the post. */
  flaggedBy: text("flagged_by").notNull(),
  /** Priority level — 'critical' instantly hides the post. */
  priority: flagPriorityEnum("priority").default("medium").notNull(),
  /** Reason for flagging. */
  reason: text("reason"),
  /** Link to the moderation record created from this flag. */
  moderationId: uuid("moderation_id").references(() => postModeration.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export type PostFlag = typeof postFlags.$inferSelect;
export type NewPostFlag = typeof postFlags.$inferInsert;

// ─── Analytics ───────────────────────────────────────────────────────────────

/**
 * Supported analytics event types.
 */
export const analyticsEventTypeEnum = pgEnum("analytics_event_type", [
  "post_view",
  "post_like",
  "post_unlike",
  "post_bookmark",
  "post_unbookmark",
  "comment_create",
  "comment_like",
  "post_share",
  "post_create",
  "poll_vote",
  "search",
  "page_view",
]);

/**
 * Stores user interaction analytics events.
 * Event-specific data is stored in the JSONB `metadata` column.
 */
export const analyticsEvents = pgTable(
  "analytics_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id").notNull(),
    type: analyticsEventTypeEnum("type").notNull(),
    /** Arbitrary event-specific payload (e.g. postId, dwellTimeMs, query). */
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    /** When the event occurred on the client. */
    clientTimestamp: timestamp("client_timestamp", {
      withTimezone: true,
    }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("idx_analytics_events_user_id").on(table.userId),
    index("idx_analytics_events_type").on(table.type),
    index("idx_analytics_events_created_at").on(table.createdAt),
  ],
);

export type AnalyticsEvent = typeof analyticsEvents.$inferSelect;
export type NewAnalyticsEvent = typeof analyticsEvents.$inferInsert;

// ─── Recommendations ─────────────────────────────────────────────────────────

/**
 * Per-user preference vector built from aggregated analytics events.
 * Used to rank recommendation candidates by cosine similarity.
 */
export const userRecommendationProfiles = pgTable(
  "user_recommendation_profiles",
  {
    userId: text("user_id").primaryKey(),
    /** Aggregated preference vector (same dimensionality as post embeddings). */
    vector: vector("vector", { dimensions: EMBEDDING_DIMENSIONS }),
    /** Number of analytics events used to build this vector. */
    eventCount: integer("event_count").notNull().default(0),
    lastGeneratedAt: timestamp("last_generated_at", {
      withTimezone: true,
    }),
    /** Start of the analytics event window used for this vector. */
    sourceWindowStart: timestamp("source_window_start", {
      withTimezone: true,
    }),
    /** End of the analytics event window used for this vector. */
    sourceWindowEnd: timestamp("source_window_end", { withTimezone: true }),
  },
);

export type UserRecommendationProfile =
  typeof userRecommendationProfiles.$inferSelect;
export type NewUserRecommendationProfile =
  typeof userRecommendationProfiles.$inferInsert;

/**
 * Status of a recommendation generation batch.
 */
export const recommendationBatchStatusEnum = pgEnum(
  "recommendation_batch_status",
  ["pending", "running", "completed", "failed"],
);

/**
 * Tracks each recommendation generation run for a user.
 */
export const recommendationBatches = pgTable("recommendation_batches", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  status: recommendationBatchStatusEnum("status").default("pending").notNull(),
  /** What triggered this generation (e.g. 'cold_start', 'low_queue', 'manual'). */
  trigger: text("trigger"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  error: text("error"),
});

export type RecommendationBatch = typeof recommendationBatches.$inferSelect;
export type NewRecommendationBatch = typeof recommendationBatches.$inferInsert;

/**
 * Individual recommended post items within a batch.
 * Ordered by rank; servedAt is set when the item is returned via the API.
 */
export const recommendationItems = pgTable(
  "recommendation_items",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    batchId: uuid("batch_id")
      .notNull()
      .references(() => recommendationBatches.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    postId: uuid("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    rank: integer("rank").notNull(),
    score: doublePrecision("score").notNull(),
    /** JSON array of reasons a post was nearly filtered out, for debugging. */
    filterReasons: jsonb("filter_reasons").$type<string[]>(),
    /** Set when the item is served to the user via the API. */
    servedAt: timestamp("served_at", { withTimezone: true }),
  },
  (table) => [
    index("idx_recommendation_items_user_unserved").on(
      table.userId,
      table.servedAt,
      table.rank,
    ),
    index("idx_recommendation_items_user_post").on(table.userId, table.postId),
  ],
);

export type RecommendationItem = typeof recommendationItems.$inferSelect;
export type NewRecommendationItem = typeof recommendationItems.$inferInsert;
