/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as ProfileFollowingRouteImport } from './routes/profile/following'
import { Route as ProfileFollowersRouteImport } from './routes/profile/followers'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminModerationIndexRouteImport } from './routes/admin/moderation/index'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFollowingRoute = ProfileFollowingRouteImport.update({
  id: '/profile/following',
  path: '/profile/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFollowersRoute = ProfileFollowersRouteImport.update({
  id: '/profile/followers',
  path: '/profile/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationIndexRoute = AdminModerationIndexRouteImport.update({
  id: '/admin/moderation/',
  path: '/admin/moderation/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/testing': typeof TestingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/testing': typeof TestingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/moderation': typeof AdminModerationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/testing': typeof TestingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/bookmarks'
    | '/explore'
    | '/notifications'
    | '/settings'
    | '/testing'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/profile/followers'
    | '/profile/following'
    | '/users/$userId'
    | '/chat/'
    | '/playground/'
    | '/profile/'
    | '/admin/moderation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/bookmarks'
    | '/explore'
    | '/notifications'
    | '/settings'
    | '/testing'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/profile/followers'
    | '/profile/following'
    | '/users/$userId'
    | '/chat'
    | '/playground'
    | '/profile'
    | '/admin/moderation'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/bookmarks'
    | '/explore'
    | '/notifications'
    | '/settings'
    | '/testing'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/profile/followers'
    | '/profile/following'
    | '/users/$userId'
    | '/chat/'
    | '/playground/'
    | '/profile/'
    | '/admin/moderation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  BookmarksRoute: typeof BookmarksRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  TestingRoute: typeof TestingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ProfileFollowersRoute: typeof ProfileFollowersRoute
  ProfileFollowingRoute: typeof ProfileFollowingRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AdminModerationIndexRoute: typeof AdminModerationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/following': {
      id: '/profile/following'
      path: '/profile/following'
      fullPath: '/profile/following'
      preLoaderRoute: typeof ProfileFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/followers': {
      id: '/profile/followers'
      path: '/profile/followers'
      fullPath: '/profile/followers'
      preLoaderRoute: typeof ProfileFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation/': {
      id: '/admin/moderation/'
      path: '/admin/moderation'
      fullPath: '/admin/moderation/'
      preLoaderRoute: typeof AdminModerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  BookmarksRoute: BookmarksRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  TestingRoute: TestingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ProfileFollowersRoute: ProfileFollowersRoute,
  ProfileFollowingRoute: ProfileFollowingRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AdminModerationIndexRoute: AdminModerationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
