/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as ApiRouteImport } from "./routes/api";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProfileIndexRouteImport } from "./routes/profile/index";
import { Route as UsersUserIdRouteImport } from "./routes/users.$userId";
import { Route as ProfileFollowingRouteImport } from "./routes/profile/following";
import { Route as ProfileFollowersRouteImport } from "./routes/profile/followers";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";

const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRoute = ApiRouteImport.update({
  id: "/api",
  path: "/api",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any);
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileFollowingRoute = ProfileFollowingRouteImport.update({
  id: "/profile/following",
  path: "/profile/following",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileFollowersRoute = ProfileFollowersRouteImport.update({
  id: "/profile/followers",
  path: "/profile/followers",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api": typeof ApiRoute;
  "/chat": typeof ChatRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/profile/followers": typeof ProfileFollowersRoute;
  "/profile/following": typeof ProfileFollowingRoute;
  "/users/$userId": typeof UsersUserIdRoute;
  "/profile/": typeof ProfileIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api": typeof ApiRoute;
  "/chat": typeof ChatRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/profile/followers": typeof ProfileFollowersRoute;
  "/profile/following": typeof ProfileFollowingRoute;
  "/users/$userId": typeof UsersUserIdRoute;
  "/profile": typeof ProfileIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api": typeof ApiRoute;
  "/chat": typeof ChatRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/profile/followers": typeof ProfileFollowersRoute;
  "/profile/following": typeof ProfileFollowingRoute;
  "/users/$userId": typeof UsersUserIdRoute;
  "/profile/": typeof ProfileIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/api"
    | "/chat"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/profile/followers"
    | "/profile/following"
    | "/users/$userId"
    | "/profile/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/api"
    | "/chat"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/profile/followers"
    | "/profile/following"
    | "/users/$userId"
    | "/profile";
  id:
    | "__root__"
    | "/"
    | "/api"
    | "/chat"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/profile/followers"
    | "/profile/following"
    | "/users/$userId"
    | "/profile/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiRoute: typeof ApiRoute;
  ChatRoute: typeof ChatRoute;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  ProfileFollowersRoute: typeof ProfileFollowersRoute;
  ProfileFollowingRoute: typeof ProfileFollowingRoute;
  UsersUserIdRoute: typeof UsersUserIdRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api": {
      id: "/api";
      path: "/api";
      fullPath: "/api";
      preLoaderRoute: typeof ApiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/": {
      id: "/profile/";
      path: "/profile";
      fullPath: "/profile/";
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/users/$userId": {
      id: "/users/$userId";
      path: "/users/$userId";
      fullPath: "/users/$userId";
      preLoaderRoute: typeof UsersUserIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/following": {
      id: "/profile/following";
      path: "/profile/following";
      fullPath: "/profile/following";
      preLoaderRoute: typeof ProfileFollowingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/followers": {
      id: "/profile/followers";
      path: "/profile/followers";
      fullPath: "/profile/followers";
      preLoaderRoute: typeof ProfileFollowersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/auth/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/auth/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/auth/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ChatRoute: ChatRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ProfileFollowersRoute: ProfileFollowersRoute,
  ProfileFollowingRoute: ProfileFollowingRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
