import { afterEach, describe, expect, it, vi } from "vitest";

import { LlmValidationService } from "@/moderation/llm-validation.service";

describe("LlmValidationService", () => {
  const setClient = (service: LlmValidationService, client: unknown) => {
    Object.defineProperty(service, "client", {
      value: client,
      configurable: true,
    });
  };

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("returns the unavailable fallback when no API client is configured", async () => {
    const service = new LlmValidationService();
    setClient(service, null);

    await expect(
      service.validateDuplicate("original", "similar", 0.98),
    ).resolves.toEqual({
      confidence: 50,
      summary: "LLM validation unavailable — API key not configured",
    });
  });

  it("parses valid JSON responses for duplicate validation", async () => {
    const create = vi.fn().mockResolvedValue({
      choices: [
        {
          message: {
            content: '{"confidence": 87, "summary": "Clearly a repost"}',
          },
        },
      ],
    });
    const service = new LlmValidationService();
    setClient(service, { chat: { completions: { create } } });

    const result = await service.validateDuplicate(
      "Breaking news here",
      "Breaking news here again",
      0.97,
    );

    expect(result).toEqual({
      confidence: 87,
      summary: "Clearly a repost",
    });
    const request = create.mock.calls[0]?.[0] as any;
    expect(request.model).toBe("gpt-4.1-mini");
    expect(request.messages[0].content).toContain("Breaking news here");
    expect(request.messages[0].content).toContain("0.9700");
  });

  it("falls back when the model returns invalid JSON", async () => {
    const service = new LlmValidationService();
    setClient(service, {
      chat: {
        completions: {
          create: vi.fn().mockResolvedValue({
            choices: [{ message: { content: "not-json" } }],
          }),
        },
      },
    });

    const result = await service.validateHarmful(
      "A suspicious sentence",
      { violence: true },
      { violence: 0.91 },
    );

    expect(result.confidence).toBe(50);
    expect(result.summary).toContain("LLM validation error");
  });

  it("fails open when the OpenAI request throws", async () => {
    const service = new LlmValidationService();
    setClient(service, {
      chat: {
        completions: {
          create: vi.fn().mockRejectedValue(new Error("rate limited")),
        },
      },
    });

    const result = await service.validateReport(
      "Post text",
      "spam",
      "Looks autogenerated",
    );

    expect(result).toEqual({
      confidence: 50,
      summary: "LLM validation error: rate limited",
    });
  });

  it("clamps confidence above the valid range", async () => {
    const service = new LlmValidationService();
    setClient(service, {
      chat: {
        completions: {
          create: vi.fn().mockResolvedValue({
            choices: [
              {
                message: {
                  content: '{"confidence": 140, "summary": "Severely harmful"}',
                },
              },
            ],
          }),
        },
      },
    });

    await expect(
      service.validateHarmful("Text", { violence: true }, { violence: 0.99 }),
    ).resolves.toEqual({
      confidence: 100,
      summary: "Severely harmful",
    });
  });

  it("clamps confidence below the valid range", async () => {
    const service = new LlmValidationService();
    setClient(service, {
      chat: {
        completions: {
          create: vi.fn().mockResolvedValue({
            choices: [
              {
                message: {
                  content: '{"confidence": -12, "summary": "Invalid report"}',
                },
              },
            ],
          }),
        },
      },
    });

    await expect(
      service.validateReport("Post text", "other", "Unclear complaint"),
    ).resolves.toEqual({
      confidence: 1,
      summary: "Invalid report",
    });
  });
});
