name: Oxlint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.json"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: oxc-project/oxlint-action@v3.0.0
        with:
          deny: correctness
          warn: suspicious
