name: Oxlint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.json"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: "pnpm"


      - name: Install dependencies
        run: pnpm i

      - name: Run Oxlint
        run: pnpm dlx oxlint --format github -D correctness -W suspicious
