name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - test-app
          - test-auth
          - test-comments
          - test-follows
          # This test will always fail in CI
          # - test-playground
          - test-polls
          - test-posts
          - test-reactions
          - test-uploads
          - test-users
          - test-messages
          - test-config

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: "pnpm"

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Install dependencies
        run: just setup

      - name: Run ${{ matrix.target }}
        run: just ${{ matrix.target }}
